[colors.bright]
black = "0x3e4452"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.cursor]
cursor = "0xabb2bf"
text = "0x282c34"

[colors.normal]
black = "0x2c323c"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x5c6370"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[colors.selection]
background = "0x3e4452"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "MesloLGS NF"

[window]
decorations = "None"
title = "Terminal"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 16
y = 16

[selection]
save_to_clipboard = true

