#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[ -f /home/jim/.dart-cli-completion/bash-config.bash ] && . /home/jim/.dart-cli-completion/bash-config.bash || true
## [/Completion]

