#!/bin/bash

# shorts
alias b='bat'
alias c='clear'
alias d='docker'
alias e='$EDITOR'
alias f='_f() { local pattern="$1"; local search_dir="${2:-.}"; find "${search_dir}" -type d -name ".git" -prune -o -type f -iname "*${pattern}*" -print 2>/dev/null; }; _f'
alias ff='clear && fastfetch'
alias g='git'
alias h='history'
alias m='$PAGER'
alias n='nvim'
alias p='ping -c 3'
alias u='(command -v pacman > /dev/null && sudo pacman -Syu --noconfirm && yay -Syu --noconfirm && yay -Yc --noconfirm) || (sudo apt update && sudo apt upgrade -y && sudo apt autoclean -y && sudo apt autoremove -y && sudo apt autopurge -y)'
alias ua='clear && printf "\n***** $HOSTNAME *****\n\n" && u && for p in $MY_PIES;do printf "\n***** $p *****\n\n" && ssh -t "$p" bash -ic "u";done'
alias uz='7z x'
alias v=vim
alias w='_f(){ clear && curl wttr.in/"$1"; };_f' 
alias z='7z a -t7z -m0=lzma2 -mx=9 -mhe=on -p -r'

# ls
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lh --color | $PAGER'
alias lla='ls -ahl --color | $PAGER'
alias ls='LC_COLLATE=C ls -h --group-directories-first --color=auto'
alias lsd="ls -lF --color | grep --color=never '^d' | $PAGER"
alias lss='ls --human-readable --size -1 -S -F | sort -r'
alias lst='ls -lth --color | $PAGER'

#grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#ps
alias psa="ps auxf"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"

# git
alias ga='git add'
alias gaa='git add -A'
alias gaac='git add -A && git commit'
alias gaacm='git add -A && git commit -m'
alias gbr='git branch'
alias gbrd='git branch -D'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gd='git diff' # Working tree changes not staged
alias gdc='git diff --cached' # Staged vs last commit
alias gdh='git diff HEAD' # Working tree vs last commit
alias gf='git fetch'
alias gl='git log --format="%C(yellow)%h %C(white)%s %C(cyan) %aN %cr"'
alias gp='git pull'
alias gpu='git push'
alias grl='git reset --soft HEAD~1'
alias gs='git status'
alias gss='git status --short'
alias gst='git stash --all'
alias gu='git reset HEAD'

# docker
alias di='docker images'

# misc
alias btc='printf "%.0f\n" $(curl -s https://blockchain.info/ticker | jq .SEK.last)'
alias cdwc='cd /appl/veryant/isCOBOL_WEBC/bin'
alias cht='cht.sh'
alias config='/usr/bin/git --git-dir=/home/jim/.cfg/ --work-tree=/home/jim'
alias dc='for x in {0..8}; do for i in {30..37}; do for a in {40..47}; do echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "; done; echo; done; done; echo ""'
alias df='df -h'
alias diff='diff --color'
alias dum='du -hsx * | sort -rh | head -10'
alias envs='env | sort | $PAGER'
alias mkcd='function _mkcd(){ mkdir -p "$1" && cd "$1"; }; _mkcd'
alias myip="ip addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{print \$2}' | cut -d/ -f 1 | head -n 1"
alias path='echo -e ${PATH//:/\\n}'
alias ports='ss -tuln'
alias pwo='sudo poweroff'
alias rbn='sudo reboot now'
alias vpnstat='if [ "$(curl -s https://ipv6-only.api.5july.net/1.0/ipcheck | jq -r .connected)" = "true" ]; then echo -e "\e[32mconnected\e[0m"; else echo -e "\e[31mnot connected\e[0m"; fi'

# nav
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

#snapper
alias snap='snapper -c root -d'
alias snaps='snapper ls'
alias snapback='sudo snapper-rollback'

#yay
# search aur and install
alias yayi='_yayi() { yay -Slq | fzf -q "$1" -m --preview "yay -Si {1}" | xargs -ro yay -S;   }; _yayi'
# search installed and remove
alias yayr='_yayr() { yay -Qq  | fzf -q "$1" -m --preview "yay -Qi {1}" | xargs -ro yay -Rns; }; _yayr'

#reflector update mirrors
alias mirror='sudo reflector -c SE -a 6 --sort rate --save /etc/pacman.d/mirrorlist'
