#!/bin/bash

# shorts
alias b='bat'
alias c='clear'
alias d='docker'
alias e='env | sort | $PAGER'
alias f='_f() { local pattern="$1"; local search_dir="${2:-.}"; find "${search_dir}" -type f -iname "*${pattern}*" -print 2>/dev/null; }; _f'
alias g='git'
alias h='history'
alias m='$PAGER'
alias n='newsboat'
alias p='sudo promtail -config.file=/etc/promtail/config.yaml'
alias u='(command -v pacman > /dev/null && sudo pacman -Syu --noconfirm && yay -Syu --noconfirm && yay -Yc --noconfirm) || (sudo apt update && sudo apt upgrade -y && sudo apt autoclean -y && sudo apt autoremove -y && sudo apt autopurge -y)'
alias ua='clear && printf "\n***** $HOSTNAME *****\n\n" && u && for p in $MY_PIES;do printf "\n***** $p *****\n\n" && ssh -t "$p" bash -ic "u";done'
alias v=vim
alias z='7z a -t7z -m0=lzma2 -mx=9 -mhe=on -p -r'
alias uz='7z x'

# ls
alias ls='LC_COLLATE=C ls -h --group-directories-first --color=auto'
alias ll='ls -lh --color | $PAGER'
alias lla='ls -ahl --color | $PAGER'
alias la='ls -A'
alias l='ls -CF'
alias lsd="ls -lF --color | grep --color=never '^d' | $PAGER"
alias lst='ls -lth --color | $PAGER'

#grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#ps
alias psa="ps auxf"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"

# git
alias ga='git add'
alias gaa='git add -A'
alias gaac='git add -A && git commit'
alias gaacm='git add -A && git commit -m'
alias gbr='git branch'
alias gbrd='git branch -D'
alias gc='git commit'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcm='git commit -m'
alias gd='git diff' # Working tree changes not staged
alias gdc='git diff --cached' # Staged vs last commit
alias gdh='git diff HEAD' # Working tree vs last commit
alias gf='git fetch'
alias gl='git log --format="%C(yellow)%h %C(white)%s %C(cyan) %aN %cr"'
alias gp='git pull'
alias gpu='git push'
# Unto last commit
alias grl='git reset --soft HEAD~1'
alias gs='git status'
alias gss='git status --short'
alias gst='git stash --all'
# Unstage
alias gu='git reset HEAD'

# docker
alias di='docker images'

# misc
alias df='df -h'
alias dc='for x in {0..8}; do for i in {30..37}; do for a in {40..47}; do echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "; done; echo; done; done; echo ""'
alias path='echo -e ${PATH//:/\\n}'
alias cht='cht.sh'

# nav
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# misc
alias btc='printf "%.0f\n" $(curl -s https://blockchain.info/ticker | jq .SEK.last)'
alias cdwc='cd /appl/veryant/isCOBOL_WEBC/bin'
alias vpnstat='if [ "$(curl -s https://ipv6-only.api.5july.net/1.0/ipcheck | jq -r .connected)" = "true" ]; then echo -e "\e[32mconnected\e[0m"; else echo -e "\e[31mnot connected\e[0m"; fi'
alias config='/usr/bin/git --git-dir=/home/jim/.cfg/ --work-tree=/home/jim'

#snapper
alias snap='snapper -c root -d'
alias snaps='snapper ls'
alias snapback='sudo snapper-rollback'

alias w='_f(){ clear && curl wttr.in/"$1"; };_f' 
#alias w='curl -sL https://www.klart.se/se/stockholms-l%C3%A4n/v%C3%A4der-solna | grep -oP "(Max|Min) temperatur\">\s*\K[^<]+" | head -2'

#yay
# search aur and install
alias yayi='_yayi() { yay -Slq | fzf -q "$1" -m --preview "yay -Si {1}" | xargs -ro yay -S;   }; _yayi'
# search installed and remove
alias yayr='_yayr() { yay -Qq  | fzf -q "$1" -m --preview "yay -Qi {1}" | xargs -ro yay -Rns; }; _yayr'

#reflector update mirrors
alias mirror='sudo reflector -c SE -a 6 --sort rate --save /etc/pacman.d/mirrorlist'
