#!/bin/bash

# shorts
alias b='bat'
alias c='clear'
alias d='docker'
alias e='$EDITOR'
f() { local pattern="$1" search_dir="${2:-.}"; find "${search_dir}" -type d -name ".git" -prune -o -type f -iname "*${pattern}*" -print 2>/dev/null; }
alias ff='clear && fastfetch -c $HOME/.config/fastfetch/default.jsonc'
alias g='git'
alias h='history'
alias mk='minikube'
alias k='minikube kubectl'
alias m='$PAGER'
alias n='nvim'
alias p='ping -c 3'
u() {
  if command -v pacman >/dev/null; then
    sudo pacman -Syu || return
    if command -v yay >/dev/null; then
      yay -Syu && yay -Yc
    fi
  elif command -v apt >/dev/null; then
    sudo apt update && sudo apt upgrade && sudo apt autoclean && sudo apt autoremove
  else
    printf 'No supported package manager found.\n' >&2
    return 1
  fi
}
alias uz='7z x'
alias v=vim
alias z='7z a -t7z -m0=lzma2 -mx=9 -mhe=on -p -r'

# ls
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lh --color | $PAGER'
alias lla='ls -ahl --color | $PAGER'
alias ls='LC_COLLATE=C ls -h --group-directories-first --color=auto'
alias lsd="ls -lF --color | grep --color=never '^d' | \$PAGER"
alias lss='ls --human-readable --size -1 -S -F | sort -r'
alias lst='ls -lth --color | $PAGER'

#grep
alias grep='grep --color=auto'
alias fgrep='grep --color=auto -F'
alias egrep='grep --color=auto -E'
alias hg='history | grep'

#ps
alias psa="ps auxf"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"

# git
alias ga='git add'
alias gaa='git add -A'
alias gaac='git add -A && git commit'
alias gaacm='git add -A && git commit -m'
alias gbr='git branch'
alias gbrd='git branch -D'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gd='git diff' # Working tree changes not staged
alias gdc='git diff --cached' # Staged vs last commit
alias gdh='git diff HEAD' # Working tree vs last commit
alias gf='git fetch'
alias gl='git log --format="%C(yellow)%h %C(white)%s %C(cyan) %aN %cr"'
alias gp='git pull'
alias gpu='git push'
alias grl='git reset --soft HEAD~1'
alias gs='git status'
alias gss='git status --short'
alias gst='git stash --all'
alias gu='git reset HEAD'

# docker
alias di='docker images'

# misc
alias btc='printf "%.0f\n" $(curl -s https://blockchain.info/ticker | jq .SEK.last)'
alias cht='cht.sh'
alias df='df -h'
alias diff='diff --color'
alias dum='du -hsx * | sort -rh | head -10'
alias envs='env | sort | $PAGER'
alias hr='fc -s'
alias path='echo -e ${PATH//:/\\n}'
alias ports='sudo ss -tulpn'
alias pwo='sudo poweroff'
alias rbn='sudo reboot now'
alias vn='vim -u NONE -N'
alias vpnstat='if [ "$(curl -s https://ipv6-only.api.5july.net/1.0/ipcheck | jq -r .connected)" = "true" ]; then echo -e "\e[32mconnected\e[0m"; else echo -e "\e[31mnot connected\e[0m"; fi'

# nav
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
# shellcheck disable=SC2012
cl() { cd "$1" && ls -lah | less; }
mkcd() { mkdir "$1" && cd "$1" || return; }

# opencode
alias oc='opencode'
alias ocr='opencode run'
alias ocu='opencode update --method curl'
alias ocs='opencode serve'

#snapper
alias snap='snapper -c root -d'
alias snaps='snapper ls'
alias snapback='sudo snapper-rollback'

#yay
# search aur and install
yayi() { yay -Slq | fzf -q "$1" -m --preview "yay -Si {1}" | xargs -ro yay -S; }
# search installed and remove
yayr() { yay -Qq | fzf -q "$1" -m --preview "yay -Qi {1}" | xargs -ro yay -Rns; }

#reflector update mirrors
alias mirror='sudo reflector -c SE -a 6 --sort rate --save /etc/pacman.d/mirrorlist'
