# If not running interactively, don't do anything
[[ $- != *i* ]] && return

HISTCONTROL=ignoreboth:erasedups # Erase duplicates
HISTIGNORE=?:??                  # Ignore one and two letter commands
HISTFILESIZE=99999               # Max size of history file
HISTSIZE=99999                   # Amount of history to preserve

if [ -d "$HOME/.bin" ]; then
	PATH="$HOME/.bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ]; then
	PATH="$HOME/.local/bin:$PATH"
fi

shopt -s autocd

export MY_PIES="jaypi pajen"
export EDITOR=vim
export PAGER=less
export BROWSER=brave
export LESS="FRsX"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto verbose"
export GIT_PS1_SHOWCOLORHINTS=1

magenta='\[\033[35m\]'
blue='\[\033[01;34m\]'
red='\[\e[31m\]'
reset='\[\e[m\]'

PROMPT_COMMAND='__git_ps1 "$magenta\u@\h:$blue\w$reset" "$(s=$?;[[ $s != 0 ]] && echo -n "$red($s)$reset")\\\$ "'

source ~/.git-prompt.sh
BASH_COMPLETION_SCRIPT="/usr/share/bash-completion/bash_completion"

if [ -f "$BASH_COMPLETION_SCRIPT" ]; then
    source "$BASH_COMPLETION_SCRIPT"
fi

source "$HOME/.bash_aliases"

bind -f ~/.inputrc
